baseURL: "https://www.beytan.net"
languageCode: "tr-tr"
title: "beytan.net"
theme: "PaperMod"

enableRobotsTXT: true

params:
  env: production
  homeInfoParams:
      Title: beytan.net
      Content: personal blog for me, myself and my lack of memory

  socialIcons:
      - name: twitter
        url: "https://twitter.com/239826"
      - name: github
        url: "https://github.com/beyti"

menu:
  main:
    - identifier: Posts
      name: Posts
      url: /posts/
      weight: 10
    - name: Categories
      url: categories/
      weight: 20
    - name: Tags
      url: tags/
      weight: 30